@baseUrl = http://localhost:5000
@urlPath = api/v1


### 
POST {{baseUrl}}/{{urlPath}}/city
Content-Type: application/json
Accept: application/json
withCredentials: true

  {
    "name": "wrocław",
    "halls": ["652a5be8cf84fd82374f2388", "652a5be8cf84fd82374f2388"]
  }

###
GET {{baseUrl}}/{{urlPath}}/cities
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/city/652a8b615695426c6a00ead4
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/city/652a8b615695426c6a00ead4
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "name": "gdansk",
  "halls": ["652a5be8cf84fd82374f2389", "652a5be8cf84fd82374f2388"]
}

###
DELETE {{baseUrl}}/{{urlPath}}/city/652a5c0b00e6d4b487ebf0ea
Content-Type: application/json
Accept: application/json
withCredentials: true


