@baseUrl = http://localhost:5000
@urlPath = api/v1


###  
POST {{baseUrl}}/{{urlPath}}/hall
Content-Type: application/json
Accept: application/json
withCredentials: true

  {
    "hallNumber": 2,
    "city": "gdańsk",
    "seats": [
        {
          "row": "A",
          "seat": "1",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "2",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "3",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "4",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "5",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "6",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "7",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "8",
          "status": "FREE",
          "type": "STANDARD"
        }
      ]
  }

###
GET {{baseUrl}}/{{urlPath}}/halls
Content-Type: application/json
Accept: application/json
withCredentials: true
 
###
GET {{baseUrl}}/{{urlPath}}/halls/WARSAW
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/hall/65b0171b9757e8662a2cca1e
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/hall/65b0171b9757e8662a2cca1e
Content-Type: application/json
Accept: application/json
withCredentials: true

  {
      "hallNumber": 3,
      "city": "BERLIN",
      "seats": [
        {
          "row": "A",
          "seat": "1",
          "status": "FREE",
          "type": "VIP"
        },
        {
          "row": "A",
          "seat": "2",
          "status": "FREE",
          "type": "VIP"
        },
        {
          "row": "A",
          "seat": "3",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "4",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "5",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "6",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "7",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "8",
          "status": "FREE",
          "type": "STANDARD"
        }
      ]
  }

###
DELETE {{baseUrl}}/{{urlPath}}/hall/652baa4ec42c4de2d1870dc2
Content-Type: application/json
Accept: application/json
withCredentials: true
