@baseUrl = http://localhost:5000
@urlPath = api/v1


###   
POST {{baseUrl}}/{{urlPath}}/show
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "hall": "659d017cd61801ac6591a2c0",
  "movie": "659c0fcc68f64efa7ba35488",
  "time": "20:00"
}

###
GET {{baseUrl}}/{{urlPath}}/shows/all
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/shows/movie/65c9d733f25ebd72f4ad922e
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/shows/BERLIN
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/shows/city/BERLIN
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/show/659d21c2255154e5bd8c163a
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "hall": "659d017cd61801ac6591a2c0",
  "movie": "659c0fcc68f64efa7ba35488",
  "time": "16:00"
}

###
DELETE {{baseUrl}}/{{urlPath}}/show/659d21a6255154e5bd8c1637
Content-Type: application/json
Accept: application/json
withCredentials: true