@baseUrl = http://localhost:5000
@urlPath = api/v1


###    
POST {{baseUrl}}/{{urlPath}}/show
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "hall": 1,
  "movie": {
    "_id": "65c9d636f25ebd72f4ad920e",
    "name": "Barbie",
    "category": [
        "COMEDY",
        "ADVENTURE"
      ],
    "img":"https://res.cloudinary.com/dandawid/image/upload/v1707745309/l6tfgxsoauixaj5clofg",
    "description": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans."
  },
  "time": "14:00",
  "city": "AMSTERDAM"
}

###
GET {{baseUrl}}/{{urlPath}}/shows/filter?movieId=65c9d733f25ebd72f4ad922e
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/shows/PARIS/65c9d692f25ebd72f4ad9227
Content-Type: application/json
Accept: application/json
withCredentials: true

###  
GET {{baseUrl}}/{{urlPath}}/shows/city/AMSTERDAM
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/shows/movie/AMSTERDAM/Aquaman and the Lost Kingdom
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/show/659d21c2255154e5bd8c163a
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "hall": "659d017cd61801ac6591a2c0",
  "movie": "659c0fcc68f64efa7ba35488",
  "time": "16:00"
}

###
DELETE {{baseUrl}}/{{urlPath}}/show/659d21a6255154e5bd8c1637
Content-Type: application/json
Accept: application/json
withCredentials: true