@baseUrl = http://localhost:5000
@urlPath = api/v1


###   
POST {{baseUrl}}/{{urlPath}}/ticket
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "movie": "659c0fcc68f64efa7ba35488",
  "show": "659d2078255154e5bd8c1633",
  "seats": [
        {
          "row": "A",
          "seat": "1",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "2",
          "status": "FREE",
          "type": "STANDARD"
        }],
  "price": 20,
  "name": {
    "name": "Daniel",
    "lastName": "Daniel",
    "email": "dd@wp.pl"
  }
}

###
GET {{baseUrl}}/{{urlPath}}/tickets
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/ticket/659d385ba72504ee3b943aef
Content-Type: application/json
Accept: application/json
withCredentials: true

### 
PUT {{baseUrl}}/{{urlPath}}/ticket/659d385ba72504ee3b943aef
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "movie": "659c0fcc68f64efa7ba35488",
  "show": "659d2078255154e5bd8c1633",
  "seats": [
        {
          "row": "A",
          "seat": "1",
          "status": "FREE",
          "type": "STANDARD"
        },
        {
          "row": "A",
          "seat": "2",
          "status": "FREE",
          "type": "STANDARD"
        }],
  "price": 20
}

###
DELETE {{baseUrl}}/{{urlPath}}/ticket/659d3825a72504ee3b943aec
Content-Type: application/json
Accept: application/json
withCredentials: true